### ISSUE TITLE
Feature 1: User can pick their Pokemon

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/final-project-2#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select their Pokemon from a list of all Pokemon

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the "Choose Pokemon" anchor and confirm their selection in a modal

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/195245892-011914fc-5487-432d-91c7-c16e93520015.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to match initial build
- [x] Update `data.sql` to populate Pokemon data correctly

### ☁️ Server Tasks

- [x] Update `server/index.js` to have route for "get" user Pokemon info
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to handle host the navbar and "Choose Pokemon" anchor
- [x] Create a component to show the modal and handle the user input
- [x] Update app component to load the navbar and basic assets

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
