### ISSUE TITLE
Feature 5: User can log in

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/final-project-2#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Sign Up, Sign In, and record their battles

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can sign up or sign in via the login screen

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/201906811-27e9adb6-c7c2-4d7f-96d8-00cb03b134ab.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to handle any persistent user data needed for calls
- [ ] Update `data.sql` to have some additional sample users

### ☁️ Server Tasks

- [ ] Update `server/index.js` to have auth routes and user call routes for info
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] Clean up Nav Bar to only have functional elements
- [ ] Make sure Login link works
- [ ] Add Icon with Pokemon display to bar
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
